### ISSUE TITLE
Missing Parameters

### ISSUE THREAD

**Issue by MrtByz** [dy1901/ecg_plot#4]
Hi for a personal project I am using your tool and i have a problem. When I'm calling plot_1 or plot_12 functions some parameters are missing. If you check the pypi page of the tool in parameters table the parameters below the "columns" are missing. Can you help me about that? Thank you

**Comment by dy1901** [comment]
> Hi for a personal project I am using your tool and i have a problem. When I'm calling plot_1 or plot_12 functions some parameters are missing. If you check the pypi page of the tool in parameters table the parameters below the "columns" are missing. Can you help me about that? Thank you

Hi, those params are for the function plot, which is a more general multi purpose function. plot_1 and plot_12 are short hands for fast simple plots. If you want a more customized plot, you should use plot instead.
