### ISSUE TITLE
how to load csv data

### ISSUE THREAD

**Issue by tejas14** [dy1901/ecg_plot#5]
I am getting this error when I load the .csv file(ECG data). Can you please help me. Thank you.

![image](https://user-images.githubusercontent.com/43086070/118357521-3859d580-b598-11eb-87e8-1476723ab56c.png)
![image](https://user-images.githubusercontent.com/43086070/118357546-59222b00-b598-11eb-8c69-2036f21dd042.png)

**Comment by dy1901** [comment]
You have to  transpose the csv file.
